### PR TITLE
Fix organization names in pathname

### LINKED ISSUE #37: Log out doesn't work properly on dashboard
The user is logged out only after a couple of clicks.

### LINKED ISSUE #39: Organization names taken from pathname
Due to the fact that the organization names taken from pathname. There are some errors with how the name is displayed to the user.
On creation and page refresh the name is taken directly from pathname and the symbols like  % are displayed. After the user changes the organization and the names display properly.

### PR DESCRIPTION
**Pull request by hubcio2115**
fixes #39 
fixes #37

# Changes
- added `dev:turbo` script
- added shadcn `Form`
- `/dasboard/` now redirects to the first organization user's in
- added `not-found.tsx`

### CODE REVIEW

File: apps/web/src/app/layout.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export default async function RootLayout({ children }: PropsWithChildren) {
   const session = await getServerAuthSession();
 
   return (
-    <html lang="en" className={GeistSans.className}>
+    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
```
Comment (kalisowski) [inline apps/web/src/app/layout.tsx:21]: Didn't know you can do that.

**Review by kalisowski — APPROVED** [review]
