### PR TITLE
Feat/9 create homepage - pricing last fixes

### LINKED ISSUE #9: Stworzyć Homepage
Strona główna powinna być na roucie `/`. Powinno to być w stylu strony głownej produktu SaaS.

### PR DESCRIPTION
**Pull request by kalisowski**

### CODE REVIEW

File: src/components/premiumPricingCard.tsx [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+          <span className="font-bold text-fuchsia-900">Premium</span> Plan
+        </CardTitle>
+        <CardDescription>
+          For large channels with even larger demands.
+        </CardDescription>
+      </CardHeader>
+      <CardContent className="mb-10 grid gap-4">
+        {featureList.map((feature, index) => (
+          <div
+            key={index}
```
Comment (hubcio2115) [inline src/components/premiumPricingCard.tsx]: Overall `keys` on map should be unique and unchangable. Using and index is [not ok](https://react.dev/learn/rendering-lists#why-does-react-need-keys). In this scenario it's fine since it's static, but in scenarios if the order'd change it can lead to a unpredictable behavior. So it should be changed to a unique value between those objects. Like `title`, `description` or add a static value of `id`.

Same thing goes for `StandardPricingCard`

File: src/components/premiumPricingCard.tsx [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+    title: "Priority Support",
+    description: "Access premium customer support 24/7.",
+  },
+  {
+    title: "Unlimited upload speeds",
+    description: "Enjoy the fastest upload speeds possible.",
+  },
+];
+
+type CardProps = React.ComponentProps<typeof Card>;
```
Comment (hubcio2115) [inline src/components/premiumPricingCard.tsx]: Without `react` import this shouldn't work. Fix this.

**Review by hubcio2115 — CHANGES_REQUESTED** [review]

**Review by hubcio2115 — APPROVED** [review]
LGTM 👍🏻
